### ISSUE TITLE
Dialogs files

### ISSUE THREAD

**Issue by rhadamants** [TimberOwls/Orience#1]
This tool extracts the dialogues of the game? I found several DDS with texts but none were the dialogues.

**Comment by Echelo** [comment]
So far, I have not related the correct .hmd file to the btxt database, but if you look at the .txt files generated by unpackhfm mode, you'll see the dialog is there in the .txt files

Similar to xiii series, the text is referred to by uv coordinates on the dds files from font_XX.bin, so I made a text file with the proper characters mapped to the inf indexes

**Comment by Echelo** [comment]
see 00000021_00000015.txt
00000021_00000015.hmd:\00000000_00000000.bin\The Dark Age ßFederation and Republic
00000021_00000015.hmd:\00000001_00000001.bin\Beyond verifying the authenticity of chronicles that supposedly predate our current age, the studious historian is also tasked with salvaging what few facts lie amid a sea of subjective observations. It is for that reason that much of what precious little we know of the time two millenia before our own comes by way of a document with no storytelling aspirations whatsoever_an airship's logbook.  The registry tells us that the vessel was one amid a fleet of dozens, all in the service of what was known as the "federation." Many infer that its primary purpose was military, as the log contains several accounts of combat with some manner of "sky-soldiers" in purported allegiance to the "republic." The prevailing historical theory holds that these two composite states, federation and republic, partook in a battle of epic proportions, each seeking to claim dominion over Orience.  While science has found that the document's age exceeds two thousand years, the veracity of historians' inferences cannot be so easily ascertained. Nevertheless, that such a simple, ordinary log could draw so much scholarly attention sets one's mind to wonder what mundane, overlooked article might survive to tell posterity of our lives. 

00000021_00000015.hmd:\00000006_00000006.bin\The Dark Age ßThe Ultima War 
00000021_00000015.hmd:\00000007_00000007.bin\It is a tale every child in Orience has been told at one time or another. In days of yore, when the peristylia had yet to grace our land and conquest was the only law, there stood four sovereign nations. Each took it upon itself to create the mightiest army the world had ever known, and when the time came, all four rode forth to wage the war to end all wars_the Ultima War. While the tale has seen its fair share of embellishments and alterations over time, one item that remains remarkably consistent is the name of the war, "Ultima." It is a curious thing, the importance children attach to names.

**Comment by rhadamants** [comment]
I found some texts in the battle us.bin. But neither was the in-game dialogues. I managed to extract battle_us.bin only once. I do not understand how this funcioa .DB3 files. Do you know if some other file has the dialogues in-game texts or texts are those DB3 files?

**Comment by Echelo** [comment]
the battle_US.bin contains .hmd files, each .hmd file contains entrys with indexes that refer to text characters from the inf files extracted from the font_US.bin

**Comment by Echelo** [comment]
The .db3 files I generated using the data\*.bin files, and the separate .bin files extracted from battle.bin.  They can be opened and edited in SQLite Expert.

**Comment by rhadamants** [comment]
What is the correct way to extract battle_us.bin and playgoprogress_us.bin. I am unable to extract battle_us.bin again

**Comment by Echelo** [comment]
Orience.exe unpackhfm battle_US.bin
I haven't updated the readme in a while, but check Program.cs for the newer modes

**Comment by rhadamants** [comment]
playgoprogress_us.bin has some text dialogue?

**Comment by Echelo** [comment]
Just one .dds file in playgoprogress
After using unpackhfm mode on the battle_US.bin
Orience.exe unpackallhmd "C:\path\to\WIN\JP\package\_unpacked\JP\battle\data\battle_US_unpacked"

**Comment by rhadamants** [comment]
And platform_us?
Battle_us.bin some texts missing letters.
00000009_00000009.hmd:\00000405_00000195.bin\eturn to Command Select
00000009_00000009.hmd:\00000551_00000227.bin\ancel
00000009_00000009.hmd:\00000552_00000228.bin\eturn to Title 
00000009_00000009.hmd:\00000616_00000268.bin\emove
00000009_00000009.hmd:\00000633_00000279.bin\etails

**Comment by Echelo** [comment]
Yeah, my separator parsing is not perfect for the .hmd sub entrys.  It can be fixed though.  

platform_US.bin:\00000000_00000000.bin\Help
platform_US.bin:\00000001_00000001.bin\View the game help.
platform_US.bin:\00000002_00000002.bin\Display
platform_US.bin:\00000003_00000003.bin\Resize
platform_US.bin:\00000004_00000004.bin\Reset
platform_US.bin:\00000005_00000005.bin\Adjust the display so the white border is visible on all sides.
platform_US.bin:\00000006_00000006.bin\Display
platform_US.bin:\00000007_00000007.bin\Adjust the screen size.
platform_US.bin:\00000008_00000008.bin\This game supports an autosave feature for system file data such as overall gameplay time. An autosave icon will appear in the upper-right wh
en saving system file data. Save campaign progress and other game data at relic terminals around Orience.
platform_US.bin:\00000009_00000009.bin\-
platform_US.bin:\00000010_0000000A.bin\hange Accounts

**Comment by rhadamants** [comment]
Rename platform_us.bin to hmd:
platform_us.hmd:\00000000_00000000.bin\ 
platform_us.hmd:\00000001_00000001.bin\         
platform_us.hmd:\00000002_00000002.bin\   
platform_us.hmd:\00000003_00000003.bin\  
platform_us.hmd:\00000004_00000004.bin\  
platform_us.hmd:\00000005_00000005.bin\                               
platform_us.hmd:\00000006_00000006.bin\   
platform_us.hmd:\00000007_00000007.bin\           
platform_us.hmd:\00000008_00000008.bin\                                                                                                                           
platform_us.hmd:\00000009_00000009.bin\
platform_us.hmd:\00000010_0000000A.bin\

**Comment by Echelo** [comment]
put platform files in the battle_XX_unpacked folder for now to get proper output

**Comment by rhadamants** [comment]
Channel?
